import PDFDocument from 'pdfkit';
import cloudinary from '../config/cloudinary.js'; 
import path from 'path';
import fs from 'fs';

export const generateAndUploadPDF = (scan) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });

    const fontPath = path.join(process.cwd(), 'fonts', 'NotoSansDevanagari-Regular.ttf');
    
    let hasHindiFont = false;
    if (fs.existsSync(fontPath)) {
      doc.registerFont('HindiFont', fontPath);
      hasHindiFont = true;
    } else {
      console.warn("WARNING: NotoSansDevanagari-Regular.ttf not found in backend/fonts/");
    }

    const cloudinaryStream = cloudinary.uploader.upload_stream(
      {
        folder: "skinshield/reports",
        format: "pdf",
        resource_type: "raw" 
      },
      (error, result) => {
        if (error) {
          console.error("Cloudinary PDF Upload Error:", error);
          return reject(error);
        }
        resolve(result.secure_url);
      }
    );

    doc.pipe(cloudinaryStream);

    doc.fontSize(24).font('Helvetica-Bold').text('SkinShield Medical Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('gray').text(`Report ID: ${scan._id}`, { align: 'center' });
    doc.moveDown(1.5);

    let badgeColor = 'green';
    if (scan.riskLevel === 'medium') badgeColor = 'orange';
    if (scan.riskLevel === 'high') badgeColor = 'red';

    doc.fontSize(16).font('Helvetica-Bold').fillColor(badgeColor)
       .text(`RISK LEVEL: ${(scan.riskLevel || 'Unknown').toUpperCase()}`, { align: 'center' });
    doc.moveDown(2);
    doc.fillColor('black'); 

    if (scan.patientName && scan.patientName !== "Unknown") {
      doc.fontSize(14).font('Helvetica-Bold').text('Patient Details', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica').text(`Name: ${scan.patientName}`);
      doc.text(`Age: ${scan.age ? scan.age + ' Years' : 'N/A'}`);
      
      const genderText = scan.gender ? scan.gender.charAt(0).toUpperCase() + scan.gender.slice(1) : 'N/A';
      doc.text(`Gender: ${genderText}`);
      doc.text(`Village/Area: ${scan.village}`);
      
      if (scan.phone) {
        doc.text(`Phone: ${scan.phone}`);
      }
      doc.moveDown(1.5);
    }

    doc.fontSize(14).font('Helvetica-Bold').text('AI Dermatologist Analysis');
    doc.moveDown(0.5);
    
    if (scan.report) {
      const containsHindi = /[\u0900-\u097F]/.test(scan.report);

      if (containsHindi && hasHindiFont) {
        doc.fontSize(12).font('HindiFont').text(scan.report, { align: 'justify' });
      } else {
        doc.fontSize(12).font('Helvetica').text(scan.report, { align: 'justify' });
      }
      
    } else {
      doc.fontSize(12).font('Helvetica').fillColor('red').text("Report generation failed.");
    }

    doc.moveDown(3);
    doc.fillColor('gray'); 

    doc.fontSize(10).font('Helvetica').fillColor('gray')
       .text('Disclaimer: This report was generated by AI (SkinShield) for informational purposes only and is not a substitute for professional medical advice. Please consult a dermatologist for a definitive diagnosis.', { align: 'center' });

    doc.end();
  });
};