import PDFDocument from 'pdfkit';
import cloudinary from '../config/cloudinary.js'; 
import path from 'path';
import fs from 'fs';

export const generateAndUploadPDF = (scan) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });

    // 1. Define the path to our custom Hindi font
    // process.cwd() points to the 'backend' folder when running node server.js
    const fontPath = path.join(process.cwd(), 'fonts', 'NotoSansDevanagari-Regular.ttf');
    
    // Check if the font actually exists before trying to register it
    let hasHindiFont = false;
    if (fs.existsSync(fontPath)) {
      doc.registerFont('HindiFont', fontPath);
      hasHindiFont = true;
    } else {
      console.warn("WARNING: NotoSansDevanagari-Regular.ttf not found in backend/fonts/");
    }

    // 2. Set up the Cloudinary upload stream
    const cloudinaryStream = cloudinary.uploader.upload_stream(
      {
        folder: "skinshield/reports",
        format: "pdf",
        resource_type: "raw" 
      },
      (error, result) => {
        if (error) {
          console.error("Cloudinary PDF Upload Error:", error);
          return reject(error);
        }
        resolve(result.secure_url);
      }
    );

    // 3. Pipe the PDF directly into Cloudinary
    doc.pipe(cloudinaryStream);

    // ─── 4. DRAW THE PDF DESIGN ──────────────────────────────────────────

    doc.fontSize(24).font('Helvetica-Bold').text('SkinShield Medical Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('gray').text(`Report ID: ${scan._id}`, { align: 'center' });
    doc.moveDown(1.5);

    // Dynamic Risk Level Badge
    let badgeColor = 'green';
    if (scan.riskLevel === 'medium') badgeColor = 'orange';
    if (scan.riskLevel === 'high') badgeColor = 'red';

    doc.fontSize(16).font('Helvetica-Bold').fillColor(badgeColor)
       .text(`RISK LEVEL: ${(scan.riskLevel || 'Unknown').toUpperCase()}`, { align: 'center' });
    doc.moveDown(2);
    doc.fillColor('black'); 

    doc.fontSize(14).font('Helvetica-Bold').text('AI Dermatologist Analysis');
    doc.moveDown(0.5);
    
    if (scan.report) {
      // 5. Check if the report contains Hindi characters using a basic Regex
      const containsHindi = /[\u0900-\u097F]/.test(scan.report);

      // If it has Hindi and we found our font file, use it. Otherwise, default to Helvetica.
      if (containsHindi && hasHindiFont) {
        doc.fontSize(12).font('HindiFont').text(scan.report, { align: 'justify' });
      } else {
        doc.fontSize(12).font('Helvetica').text(scan.report, { align: 'justify' });
      }
      
    } else {
      doc.fontSize(12).font('Helvetica').fillColor('red').text("Report generation failed.");
    }

    doc.moveDown(3);
    doc.fillColor('gray'); 

    // Footer / Disclaimer
    doc.fontSize(10).font('Helvetica').fillColor('gray')
       .text('Disclaimer: This report was generated by AI (SkinShield) for informational purposes only and is not a substitute for professional medical advice. Please consult a dermatologist for a definitive diagnosis.', { align: 'center' });

    // 6. Tell PDFKit to finish the file
    doc.end();
  });
};