// File: frontend/src/constants/symptoms.js

export function getSymptomQuestions(t) {
  return [
    {
      key: 'mainConcern',
      label: t('q_main_concern', 'What is the main concern bringing you in today?'),
      type: 'select',
      options: [
        { value: 'Rash', label: t('concern_rash', 'Rash') },
        { value: 'Acne / Pimples', label: t('concern_acne', 'Acne / Pimples') },
        { value: 'Itching', label: t('concern_itching', 'Itching') },
        { value: 'Pigmentation / Dark spots', label: t('concern_pigment', 'Pigmentation / Dark spots') },
        { value: 'Mole / Growth', label: t('concern_mole', 'Mole / Growth') },
        { value: 'Dry skin', label: t('concern_dry', 'Dry skin') },
        { value: 'Hair loss / scalp issue', label: t('concern_hair', 'Hair loss / scalp issue') },
        { value: 'Infection (fungal / bacterial)', label: t('concern_infection', 'Infection (fungal / bacterial)') },
        { value: 'Skin allergy', label: t('concern_allergy', 'Skin allergy') },
        { value: 'Wound / ulcer', label: t('concern_wound', 'Wound / ulcer') },
        { value: 'Nail problem', label: t('concern_nail', 'Nail problem') },
        { value: 'Other', label: t('concern_other', 'Other (Specify)') },
      ],
    },
    {
      key: 'durationDays',
      label: t('q_duration', 'How long have you had this rash/spot/acne?'),
      type: 'select',
      options: [
        { value: 'Less than 24 hours', label: t('dur_lt24h', 'Less than 24 hours') },
        { value: '1–3 days', label: t('dur_1_3d', '1–3 days') },
        { value: '1 week', label: t('dur_1w', '1 week') },
        { value: '2–4 weeks', label: t('dur_2_4w', '2–4 weeks') },
        { value: '1–3 months', label: t('dur_1_3m', '1–3 months') },
        { value: '3–6 months', label: t('dur_3_6m', '3–6 months') },
        { value: 'More than 6 months', label: t('dur_gt6m', 'More than 6 months') },
        { value: 'More than 1 year', label: t('dur_gt1y', 'More than 1 year') },
      ],
    },
    {
      key: 'symptoms',
      label: t('q_symptoms', 'Does the area itch, burn, or hurt?'),
      type: 'select',
      options: [
        { value: 'No symptoms', label: t('sym_none', 'No symptoms') },
        { value: 'Mild itching', label: t('sym_mild', 'Mild itching') },
        { value: 'Severe itching', label: t('sym_severe', 'Severe itching') },
        { value: 'Burning sensation', label: t('sym_burning', 'Burning sensation') },
        { value: 'Painful', label: t('sym_painful', 'Painful') },
        { value: 'Tingling', label: t('sym_tingling', 'Tingling') },
        { value: 'Swelling', label: t('sym_swelling', 'Swelling') },
        { value: 'Multiple symptoms', label: t('sym_multiple', 'Multiple symptoms') },
      ],
    },
    {
      key: 'priorTreatment',
      label: t('q_prior_treatment', 'Have you tried any creams or treatments already?'),
      type: 'select',
      options: [
        { value: 'No treatment yet', label: t('tx_none', 'No treatment yet') },
        { value: 'Over-the-counter cream', label: t('tx_otc', 'Over-the-counter cream') },
        { value: 'Home remedies', label: t('tx_home', 'Home remedies') },
        { value: 'Prescription medicine', label: t('tx_rx', 'Prescription medicine') },
        { value: 'Herbal / Ayurvedic', label: t('tx_herbal', 'Herbal / Ayurvedic treatment') },
        { value: 'Antibiotic cream', label: t('tx_antibiotic', 'Antibiotic cream') },
        { value: 'Steroid cream', label: t('tx_steroid', 'Steroid cream') },
        { value: 'Multiple treatments tried', label: t('tx_multiple', 'Multiple treatments tried') },
      ],
    },
    {
      key: 'allergies',
      label: t('q_allergies', 'Do you have any known allergies or skin sensitivities?'),
      type: 'select',
      options: [
        { value: 'No known allergies', label: t('al_none', 'No known allergies') },
        { value: 'Cosmetic products', label: t('al_cosmetic', 'Cosmetic products') },
        { value: 'Soap / detergent', label: t('al_soap', 'Soap / detergent') },
        { value: 'Food allergy', label: t('al_food', 'Food allergy') },
        { value: 'Medication allergy', label: t('al_meds', 'Medication allergy') },
        { value: 'Dust / pollen', label: t('al_dust', 'Dust / pollen') },
        { value: 'Metal / jewelry', label: t('al_metal', 'Metal / jewelry') },
        { value: 'Sunlight sensitivity', label: t('al_sunlight', 'Sunlight sensitivity') },
        { value: 'Other', label: t('al_other', 'Other (Specify)') },
      ],
    },
    {
      key: 'skincareRoutine',
      label: t('q_skincare', 'What is your current daily skincare routine?'),
      type: 'select',
      options: [
        { value: 'No skincare routine', label: t('sk_none', 'No skincare routine') },
        { value: 'Soap only', label: t('sk_soap', 'Soap only') },
        { value: 'Face wash + moisturizer', label: t('sk_fw_moi', 'Face wash + moisturizer') },
        { value: 'Face wash + sunscreen', label: t('sk_fw_spf', 'Face wash + sunscreen') },
        { value: 'Full routine (cleanser, moisturizer, sunscreen)', label: t('sk_full', 'Full skincare routine') },
        { value: 'Uses makeup regularly', label: t('sk_makeup', 'Uses makeup regularly') },
        { value: 'Uses medicated products', label: t('sk_med', 'Uses medicated products') },
        { value: 'Uses home remedies', label: t('sk_home', 'Uses home remedies') },
      ],
    },
    {
      key: 'currentMedications',
      label: t('q_medications', 'Are you taking any medications or supplements?'),
      type: 'select',
      options: [
        { value: 'No medications', label: t('med_none', 'No medications') },
        { value: 'Antibiotics', label: t('med_ab', 'Antibiotics') },
        { value: 'Hormonal medications', label: t('med_hormone', 'Hormonal medications') },
        { value: 'Steroids', label: t('med_steroid', 'Steroids') },
        { value: 'Vitamin supplements', label: t('med_vit', 'Vitamin supplements') },
        { value: 'Skin-related medication', label: t('med_skin', 'Skin-related medication') },
        { value: 'Chronic disease medication', label: t('med_chronic', 'Chronic disease medication (diabetes, BP etc.)') },
        { value: 'Multiple medications', label: t('med_multi', 'Multiple medications') },
      ],
    },
    {
      key: 'familyHistory',
      label: t('q_family', 'Has anyone in your family had skin conditions/cancer?'),
      type: 'select',
      options: [
        { value: 'No family history', label: t('fam_none', 'No family history') },
        { value: 'Acne', label: t('fam_acne', 'Acne') },
        { value: 'Psoriasis', label: t('fam_psor', 'Psoriasis') },
        { value: 'Eczema', label: t('fam_eczema', 'Eczema') },
        { value: 'Skin cancer', label: t('fam_cancer', 'Skin cancer') },
        { value: 'Pigmentation disorders', label: t('fam_pigment', 'Pigmentation disorders') },
        { value: 'Fungal infections', label: t('fam_fungal', 'Fungal infections') },
        { value: 'Not sure', label: t('fam_unsure', 'Not sure') },
      ],
    },
    {
      key: 'sunExposure',
      label: t('q_sun', 'What is your typical sun exposure?'),
      type: 'select',
      options: [
        { value: 'Mostly indoors', label: t('sun_indoors', 'Mostly indoors') },
        { value: 'Less than 1 hour/day', label: t('sun_lt1h', 'Less than 1 hour/day') },
        { value: '1–3 hours/day', label: t('sun_1_3h', '1–3 hours/day') },
        { value: 'More than 3 hours/day', label: t('sun_gt3h', 'More than 3 hours/day') },
        { value: 'Outdoor job', label: t('sun_outdoor', 'Outdoor job') },
        { value: 'Uses sunscreen regularly', label: t('sun_spf_yes', 'Uses sunscreen regularly') },
        { value: 'Rarely uses sunscreen', label: t('sun_spf_rare', 'Rarely uses sunscreen') },
        { value: 'Never uses sunscreen', label: t('sun_spf_no', 'Never uses sunscreen') },
      ],
    },
    {
      key: 'physicalChanges',
      label: t('q_physical', 'Have you noticed any changes in size, shape, or color?'),
      type: 'select',
      options: [
        { value: 'No changes', label: t('chg_none', 'No changes') },
        { value: 'Increased size', label: t('chg_size', 'Increased size') },
        { value: 'Changed color', label: t('chg_color', 'Changed color') },
        { value: 'Changed shape', label: t('chg_shape', 'Changed shape') },
        { value: 'Bleeding', label: t('chg_bleed', 'Bleeding') },
        { value: 'Crusting', label: t('chg_crust', 'Crusting') },
        { value: 'Rapid growth', label: t('chg_rapid', 'Rapid growth') },
        { value: 'Multiple changes', label: t('chg_multi', 'Multiple changes observed') },
      ],
    },
  ];
}

export const initialSymptoms = {
  mainConcern: 'Rash',
  durationDays: '1–3 days',
  symptoms: 'No symptoms',
  priorTreatment: 'No treatment yet',
  allergies: 'No known allergies',
  skincareRoutine: 'No skincare routine',
  currentMedications: 'No medications',
  familyHistory: 'No family history',
  sunExposure: 'Mostly indoors',
  physicalChanges: 'No changes',
};